name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo A String
        run: echvo "Hello World"
      - name: Multiline Script
        run: |
          node -v
          python -V
          npm -v
