name: Shell Commands

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo A String
        run: echo "Hello World"
      - name: Multiline Script
        run: |
          node -v
          python -V
          npm -v
      - name: Python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
